Make Contract Addresses configurable
Azuro-protocol/sdk pull request #1
Opened 2022-06-07 18:10 UTC by mabalashov

Updated Contract Addresses
Implemented the method `setContractAddresses` to be able to change the Contract Addresses
Renamed `constants.ts` -> `config.ts` due to it is not constants anymore
Renamed `contracts.d.ts` -> `contracts.ts` due to was not able to import types

2022-06-08 05:11 UTC, pavelivanov requested changes

2022-06-08 05:11 UTC, pavelivanov commented on src/contracts/config.ts
> +      return state.contractAddresses.usdt || '0xf5f125ffFFe359f2Bfe44776B5604eDFa82A0Ff2'
remove default addresses from here.

2022-06-08 05:11 UTC, pavelivanov commented on src/contracts/state.ts
> +  }
remove these conditions. User should pass all addresses w/o exceptions.

2022-06-08 05:11 UTC, pavelivanov commented on src/contracts/state.ts
> +  }
add description to the readme that user should pass addresses during configuration process.

https://sdk-docs-eta.vercel.app/get-started#configure

Repo: https://github.com/Azuro-protocol/sdk-docs

2022-06-10 06:10 UTC, mabalashov commented
BTW, do you keep the commit history clear?
I see several commits were created during the merging. Actually, I am not sure, if it possible to squash commits of PR during the merging it in the main branch in GitHub
So, please let me know, if it is important

2022-06-12 18:49 UTC, closed without merging

2022-06-12 18:49 UTC, mabalashov commented
https://github.com/Azuro-protocol/sdk/pull/2