deBridge feature
Azuro-protocol/sdk pull request #21
Opened 2024-04-11 15:20 UTC by CleanBread

2024-04-12 14:42 UTC, on47sky requested changes

2024-04-12 14:42 UTC, on47sky commented on src/hooks/useDeBridgeBet.ts
> +      referralCode: '9126',
dynamic prop

2024-04-12 14:42 UTC, on47sky commented on src/hooks/useDeBridgeSupportedTokens.ts
> +    const response = await fetch(`${deBridgeUrl}/token-list?chainId=42161`)
pass `chainId` query param from props

2024-04-12 14:42 UTC, on47sky commented on src/hooks/useDeBridgeSupportedTokens.ts
> +    enabled,
mb `enabled: Boolean(chainId && enabled)`?

2024-04-15 07:01 UTC, CleanBread commented on src/hooks/useDeBridgeBet.ts
> +      referralCode: '9126',
344bd4aa812c217f7ae2ac904a407107740f1235

2024-04-15 07:02 UTC, CleanBread commented on src/hooks/useDeBridgeSupportedTokens.ts
> +    const response = await fetch(`${deBridgeUrl}/token-list?chainId=42161`)
8aeed0c686805f9ab7bdd47cc30f9d7598cfd974

2024-04-15 07:02 UTC, CleanBread commented on src/hooks/useDeBridgeSupportedTokens.ts
> +    enabled,
chainId is required prop

2024-04-15 07:29 UTC, on47sky approved these changes

2024-04-15 08:21 UTC, merged