Flush cache of Contracts on changing ContractAddresses and WalletProvider
Azuro-protocol/sdk pull request #4
Opened 2022-06-18 13:16 UTC by mabalashov

We are using the cached Contracts and once we have changed the Contract Addresses or Wallet Provider we are still using these Contracts created with old values

2022-06-19 00:54 UTC, pavelivanov approved these changes

2022-06-19 00:55 UTC, pavelivanov requested changes

2022-06-19 00:55 UTC, pavelivanov commented on src/contracts/state.ts
> +  state.readContracts = {} as any;
why this action performs contracts flushing? It should just change a provider.

2022-06-19 00:55 UTC, pavelivanov commented on src/contracts/state.ts
>  export const setWallerProvider = (walletProvider: Web3Provider) => {
typo in Wallet

2022-06-19 14:39 UTC, mabalashov commented on src/contracts/state.ts
> +  state.readContracts = {} as any;
The Contracts cached in the state were created with old WalletProvider and old ContractAddresses.

Once we are changing any of these values, the cached Contracts should be flushed, otherwise, we have no chance at all to use the contract with another address

In my opinion, the flushing of the cache is a part of the action "change the Contract Address" because the real address will never be changed without this flushing

As an option, the method "flushState" can be created

2022-06-19 14:41 UTC, mabalashov commented on src/contracts/state.ts
>  export const setWallerProvider = (walletProvider: Web3Provider) => {
Could be fixed in a separate PR
The major version of the package should be incremented due to this method is already exporting outside

2022-06-20 06:06 UTC, pavelivanov approved these changes

2022-06-20 06:06 UTC, merged