Implementing option "from" in fetchGames method
Azuro-protocol/sdk pull request #9
Opened 2022-07-01 18:53 UTC by mabalashov

2022-07-01 19:00 UTC, mabalashov commented
I have to pass the latest block from fetchConditions to update statistics **only** after fetching all games data

The problems: sometimes we can face errors during fetching games data. But we are not stopping processing. In this case some games data could be missed
Ideally we need to implement full pagination

2022-07-04 11:09 UTC, pavelivanov requested changes

2022-07-04 11:09 UTC, pavelivanov commented on src/contracts/statistics.ts
> +export default statistics
Basically it named `stats`.

2022-07-04 11:09 UTC, pavelivanov commented on src/api/fetchConditions.ts
> +  latestBlock: number,
remove `,` from types

2022-07-04 11:09 UTC, pavelivanov commented on src/api/fetchConditions.ts
> +  const events = await coreContract.queryFilter(createdFilter, props.from)
`props` is optional

2022-07-05 07:21 UTC, merged